---
title: "SQL optimization for 2 tables"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: show 
#date: "`r Sys.Date()`"

---

<style type="text/css">
  body{
  font-size: 12pt;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T,warning=F,message=F,comment='',
                      connection = "con")

suppressWarnings(
  suppressMessages(
    suppressPackageStartupMessages({
      library(stats)
      library(MASS)
      library(tidyverse)
      library(magrittr)
      library(DBI)
      library(RSQLite)
    })
  )
)
options(scipen=100,digits=3)

con=dbConnect(SQLite(), ":memory:")
```

## make short and long table
```{sql}
drop table if exists short;
```
```{sql}
create table short as
with  tmp1 as (
    select 1 as x
    union all
    select x+1 from tmp1 where x<1e3
  )
select 
	x as id
	, lower(hex(randomblob(4))) as name
	, lower(hex(randomblob(16))) as address
	, cast(abs(random()%1e10) as integer)  as tel
	, abs(random()%100) as age
	from tmp1
;
```

```{sql}
select count(1) from short; 
```
```{sql}
select * from short limit 5;
```

```{sql}
drop table if exists long;
```
```{sql}
create table long as
with  tmp1 as (
    select 1 as x
    union all
    select x+1 from tmp1 where x<1e7
  )
select 
	abs(random()%900)+1 as id
	, date('now', printf('-%d days', abs(random()%365))) as day
	, abs(random()%10)+1 as val
	from tmp1
;
```

```{sql}
select count(1) from long;
```
```{sql}
select * from long limit 5;
```
```{sql}
select count(distinct id) from long;
```



## before indexing

```{sql}
explain query plan
select id, name, address, tel, age, day, val from short
join long using(id)
;
```
Result: 10000000 rows returned in 38790ms

```{sql}
explain query plan
select id, name, address, tel, age, day, val from long
join short using(id)
;
```
Result: 10000000 rows returned in 3192ms

```{sql}
explain query plan
select id, name, address, tel, age, count(1) as n from long
join short using(id)
group by id
;
```
Result: 900 rows returned in 17305ms

```{sql}
explain query plan
select id, name, address, tel, age, count(1) as n from long
join short using(id)
group by id having n<11000
;
```
Result: 126 rows returned in 18391ms

```{sql}
explain query plan
select id, name, address, tel, age, sum(val) as cum from long
join short using(id)
group by id
;
```
Result: 900 rows returned in 20314ms

```{sql}
explain query plan
select id, name, address, tel, age, sum(val) as cum from long
join short using(id)
group by id having cum<61000
;
```
Result: 380 rows returned in 20085ms

```{sql}
explain query plan
with tmp1 as(
	select *, count(1) as n from long
	group by id
)
select short.id, name, address, tel, age
from short
join tmp1 on short.id=tmp1.id and n<11000
;
```
Result: 126 rows returned in 13470ms

```{sql}
explain query plan
with tmp1 as(
	select *, sum(val) as cum from long
	group by id
)
select short.id, name, address, tel, age
from short
join tmp1 on short.id=tmp1.id and cum<61000
;
```
Result: 380 rows returned in 14238ms

```{sql}
explain query plan
select distinct id, name, address, tel, age from short
join long using(id)
;
```
Result: 900 rows returned in 13946ms

```{sql}
explain query plan
select * from short
where id in(select id from long)
;
```
Result: 900 rows returned in 2268ms

```{sql}
explain query plan
select * from short
where exists(select 1 from long where long.id=short.id) 
;
```
Result: 900 rows returned in 48987ms

```{sql}
explain query plan
select * from short
where id in(
	select id from long
	group by id having count(1)<11000
)
;
```
Result: 126 rows returned in 12255ms

```{sql}
explain query plan
select * from short
where exists (select 1 from long 
  where long.id=short.id 
  group by id having count(1)<11000
)
;
```
Result: 126 rows returned in 511341ms
Result: 126 rows returned in 503609ms

```{sql}
explain query plan
with tmp1 as(
	select id from long
	group by id having count(1)<11000
)
select * from short
where exists(select 1 from tmp1 where tmp1.id=short.id) 
;
```
Result: 126 rows returned in 12527ms



## after indexing

```{sql}
drop index if exists idx_id;
create unique index idx_id on short(id);
```

```{sql}
drop index if exists idx_id_long;
create index idx_id_long on long(id);
```


```{sql}
explain query plan
select id, name, address, tel, age, day, val from short
join long using(id)
;
```
Result: 10000000 rows returned in 1828ms

```{sql}
explain query plan
select id, name, address, tel, age, day, val from long
join short using(id)
;
```
Result: 10000000 rows returned in 1857ms

```{sql}
explain query plan
select id, name, address, tel, age, count(1) as n from long
join short using(id)
group by id
;
```
Result: 900 rows returned in 2392ms

```{sql}
explain query plan
select id, name, address, tel, age, count(1) as n from long
join short using(id)
group by id having n<11000
;
```
Result: 126 rows returned in 2179ms

```{sql}
explain query plan
select id, name, address, tel, age, sum(val) as cum from long
join short using(id)
group by id
;
```
Result: 900 rows returned in 10741ms

```{sql}
explain query plan
select id, name, address, tel, age, sum(val) as cum from long
join short using(id)
group by id having cum<61000
;
```
Result: 380 rows returned in 10831ms

```{sql}
explain query plan
with tmp1 as(
	select *, count(1) as n from long
	group by id
)
select short.id, name, address, tel, age
from short
join tmp1 on short.id=tmp1.id and n<11000
;
```
Result: 126 rows returned in 714ms

```{sql}
explain query plan
with tmp1 as(
	select *, sum(val) as cum from long
	group by id
)
select short.id, name, address, tel, age
from short
join tmp1 on short.id=tmp1.id and cum<61000
;
```
Result: 380 rows returned in 9058ms

```{sql}
explain query plan
select distinct id, name, address, tel, age from short
join long using(id)
;
```
Result: 900 rows returned in 3407ms

```{sql}
explain query plan
select * from short
where id in(select id from long)
;
```
Result: 900 rows returned in 759ms

```{sql}
explain query plan
select * from short
where exists(select 1 from long where long.id=short.id) 
;
```
Result: 900 rows returned in 6ms

```{sql}
explain query plan
select * from short
where id in(
	select id from long
	group by id having count(1)<11000
)
;
```
Result: 126 rows returned in 549ms

```{sql}
explain query plan
select * from short
where exists (select 1 from long 
  where long.id = short.id 
  group by id having count(1) <11000
)
;
```
Result: 126 rows returned in 675ms

```{sql}
explain query plan
with tmp1 as(
	select id from long
	group by id having count(1)<11000
)
select * from short
where exists(select 1 from tmp1 where tmp1.id=short.id) 
;
```
Result: 126 rows returned in 555ms

